immich_api_key: demo
immich_url: https://demo.immich.app

album:
  - 75c4860f-d31c-4dac-9831-0e67c7ab7668

# Clock
show_time: true
time_format: 12 # 12 or 24
show_date: true # true or false
date_format: MM/DD/YYYY
clock_source: client

# Kiosk behaviour
refresh: 30 # in seconds

layout: splitview # which layout to use. single, splitview or splitview-landscape

# Transition options
transition: cross-fade # cross-fade, fade or none

# Image display settings
show_progress: true # display a progress bar
image_fit: cover # how the image fits the screen. Options are none, contain and cover
image_effect: smart-zoom

## Image METADATA
show_album_name: true
show_person_name: true
show_image_time: true
image_time_format: 24
show_image_date: true
image_date_format: YYYY-DD-MM
show_image_description: true
show_image_exif: true
show_image_location: true
show_image_id: false
show_more_info: true
show_more_info_image_link: true
show_more_info_qr_code: true

weather:
  - name: London
    lat: 51.5285262
    lon: -0.2663999
    api:
    unit: metric
    lang: en
    default: true

kiosk:
  port: 3000

  http_timeout: -1

  redirects:
    - name: curated
      url: /

    - name: all-images
      url: /?album=none

    - name: fade-transition
      url: /?transition=fade

    - name: simple
      url: /?album=none&image_effect=none&layout=single&image_fit=contain&transition=none&disable_ui=true&show_more_info=false

    - name: solid-theme
      url: /?theme=solid
