version: "3"
env:
  VERSION: 0.0.4

tasks:
  default:
    deps: [build]
    cmds:
      - DEBUG=true ./dist/kiosk

  copy-config:
    cmds:
      - cp config.example.yaml config

  build:
    deps: [copy-config]
    cmds:
      - go build -o dist/kiosk .

  docker-image:
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} -t damongolding/immich-kiosk:{{.VERSION}} -t damongolding/immich-kiosk:latest .

  docker-image-push:
    cmds:
      - docker build --build-arg VERSION={{.VERSION}} --platform linux/amd64,linux/arm64 --push -t damongolding/immich-kiosk:{{.VERSION}} -t damongolding/immich-kiosk:latest .
