version: "3"
env:
  VERSION: 0.21.2-beta.1

includes:
  frontend:
    taskfile: ./taskfile.frontend.yml
    flatten: true

  docker:
    taskfile: ./taskfile.docker.yml
    flatten: true

tasks:
  # Development tasks
  default:
    desc: Run kiosk in debug mode
    deps: [build]
    cmds:
      - KIOSK_DEBUG=true ./dist/kiosk

  verbose:
    desc: Run kiosk in verbose debug mode
    deps: [build-verbose]
    cmds:
      - KIOSK_DEBUG_VERBOSE=true ./dist/kiosk

  # Backend tasks
  templ:
    desc: Generate templ templates
    cmds:
      - go tool templ generate

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  # Build tasks
  build:
    desc: Build kiosk
    deps: [frontend, templ]
    cmds:
      - CGO_ENABLED=0 go build -installsuffix cgo -ldflags "-X main.version={{.VERSION}}" -o dist/kiosk .

  build-verbose:
    desc: Build kiosk with face detection debugging enabled
    deps: [frontend, templ]
    cmds:
      - CGO_ENABLED=0 go build -installsuffix cgo -ldflags "-X main.version={{.VERSION}} -X github.com/damongolding/immich-kiosk/routes.drawFacesOnImages=true" -o dist/kiosk .

  # Maintenance tasks
  install:
    desc: Install development dependencies
    deps: [frontend-install]
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5
      - go mod tidy

  outdated:
    desc: Check for outdated dependencies
    cmds:
      - go list -u -m -json all | go tool go-mod-outdated -direct -update
      - cd frontend && pnpm outdated

  openapi:
    desc: Generate OpenAPI specification
    cmds:
      - go tool oapi-codegen --generate types,client -package immich_open_api https://raw.githubusercontent.com/immich-app/immich/refs/heads/main/open-api/immich-openapi-specs.json > internal/immich_open_api/immich_open_api.go
