version: "3"
env:
  VERSION: 0.30.1

includes:
  frontend:
    taskfile: ./taskfile.frontend.yml
    flatten: true

  docker:
    taskfile: ./taskfile.docker.yml
    flatten: true

tasks:
  # Development tasks
  default:
    desc: Run kiosk
    deps: [build]
    cmds:
      - ./dist/kiosk

  dev:
    desc: Run kiosk in development mode
    cmds:
      - go tool air

  verbose:
    desc: Run kiosk in verbose debug mode
    cmds:
      - go tool air -build.cmd="task build-verbose" -build.full_bin="KIOSK_DEBUG_VERBOSE=true ./dist/kiosk"

  # Backend tasks
  templ:
    desc: Generate templ templates
    cmds:
      - go tool templ generate

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run
      - cd frontend && pnpm lint

  # Build tasks
  build:
    desc: Build kiosk
    deps: [frontend, templ]
    cmds:
      - CGO_ENABLED=0 go build -installsuffix cgo -ldflags "-X main.version={{.VERSION}}" -o dist/kiosk .

  build-verbose:
    desc: Build kiosk with face detection debugging enabled
    deps: [frontend, templ]
    cmds:
      - CGO_ENABLED=0 go build -installsuffix cgo -ldflags "-X main.version={{.VERSION}} -X github.com/damongolding/immich-kiosk/routes.drawFacesOnImages=true" -o dist/kiosk .

  # Maintenance tasks
  install:
    desc: Install development dependencies
    deps: [frontend-install]
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5
      - go mod tidy

  update-go:
    desc: Sync local Go version with go.mod and Dockerfile
    cmds:
      - |
        GO_VERSION_FULL=$(go version | awk '{print $3}' | sed 's/go//')
        echo "ðŸ“¦ Updating go.mod to use Go $GO_VERSION_FULL"
        go mod edit -go=$GO_VERSION_FULL

        echo "ðŸ› ï¸  Updating Dockerfile to use Go $GO_VERSION_FULL"
        sed -i.bak -E "s|golang:[0-9]+\.[0-9]+(\.[0-9]+)?-[[:alnum:]-]+|golang:${GO_VERSION_FULL}-bookworm|g" Dockerfile

        echo "--- Dockerfile diff ---"
        diff Dockerfile.bak Dockerfile || true
        rm Dockerfile.bak

  outdated-go:
    desc: Check for outdated Go dependencies
    cmds:
      - (printf "Module\tCurrent\tLatest\n" && go list -u -m -json all | jq -r 'select(.Main or .Indirect | not) | select(.Update) | [.Path, .Version, .Update.Version] | @tsv') | column -t -s $'\t'

  outdated:
    desc: Check for outdated Go and frontend dependencies
    deps: [outdated-go, frontend-outdated]

  openapi:
    desc: Generate OpenAPI specification
    cmds:
      - go tool oapi-codegen --generate types,client -package immich_open_api https://raw.githubusercontent.com/immich-app/immich/refs/heads/main/open-api/immich-openapi-specs.json > internal/immich_open_api/immich_open_api.go
